title: Matrix Calculator
remote_theme : "manid2/lone-wolf-theme"
markdown: CommonMarkGhPages
description: This is a python based Android application used to simply calculate Determinant of provided Matrix.

